### ISSUE TITLE
CallSupport customFields question

### ISSUE THREAD

**Issue by mlg87** [RobertSheaO/react-native-zendesk-support#1]
hey man, great package. way better than having to use a WebView for zendesk in RN. so this is probably due to my inexperience with native development (js background) but is the intention of the `customFields` param on the `callSupport` method to add meta data to the ticket? from reading the `RNZenDeskSupport.m` file and the zendesk docs, it seems like a new form field should be created.

**Comment by RobertSheaO** [comment]
Custom fields, at least in this implementation, are to gather data from the user's device. I use it to grab device id, type, what version of my app is running, what their device language is set to, ect. You can use react-native-device-info to get this information if you'd like to gather the same information.

Your data can certainly come from form fields if you'd like, just put them into the object and match them to the custom field ID's that the ZenDesk portal gives you when you define the custom fields.

https://support.zendesk.com/hc/en-us/articles/203661496-Adding-custom-fields-to-your-tickets-and-support-request-forms

**Comment by mkpietrzyk** [comment]
@RobertSheaO 

Hi! I am trying to get exactly what you said about filling the data of custom fields with the app version etc. using device-info and the formID i took from Zendesk. Yet the custom fields are not filled with the data. 

for example my version custom ticket ID number is 1423213

when using code 

const customFields = {
      1423213: DeviceInfo.getVersion(),
    };

ZendeskSupport.callSupport(customFields);

Am I doing something wrong?

**Comment by RobertSheaO** [comment]
Please note: Zendesk requires that custom fields be enabled AND editable in order for the SDK to populate the fields. This is a requirement of their SDK, not this package.
