### ISSUE TITLE
flag activity new task required while on Samsung/Marshmallow.

### ISSUE THREAD

**Issue by mkpietrzyk** [RobertSheaO/react-native-zendesk-support#10]
Hi! 

I have started using library and I have encountered a problem on Android Marshmallow 6.0.1

RN 0.49.2

I have created a button which calls Support on click. While on Huawei device (with Android 7.0) everything works like a charm, on Samsung(with Android 6.0.1) the following error occurs or the app crashes: 

> 10-17 18:08:58.331 15980 16070 E unknown:ReactNative: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
> 
> 10-17 18:08:58.331 15980 16070 E unknown:ReactNative:   at android.app.ContextImpl.startActivity(ContextImpl.java:747)
> 
> 10-17 18:08:58.331 15980 16070 E unknown:ReactNative:   at android.app.ContextImpl.startActivity(ContextImpl.java:734)
> 
> 10-17 18:08:58.331 15980 16070 E unknown:ReactNative:   at android.content.ContextWrapper.startActivity(ContextWrapper.java:345)
> 
> 10-17 18:08:58.331 15980 16070 E unknown:ReactNative:   at android.content.ContextWrapper.startActivity(ContextWrapper.java:345)
> 
> 10-17 18:08:58.331 15980 16070 E unknown:ReactNative:   at com.zendesk.sdk.feedback.ui.ContactZendeskActivity.startActivity(ContactZendeskActivity.java:102)
> 
> 10-17 18:08:58.331 15980 16070 E unknown:ReactNative:   at com.robertsheao.RNZenDeskSupport.RNZenDeskSupportModule.callSupport(RNZenDeskSupportModule.java:231)
> 
> 10-17 18:08:58.331 15980 16070 E unknown:ReactNative:   at java.lang.reflect.Method.invoke(Native Method)
> 
> 10-17 18:08:58.331 15980 16070 E unknown:ReactNative:   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)

I have tried multiple solutions, but there were regarding real SDK integration. I am not that much into Java, but it seems connected to Intents. Yet, no solution worked for me.

**Comment by mkpietrzyk** [comment]
I will try to test my solution tommorow since I do not have access to the Samsung device now. If it will work, I will post it there.

**Comment by RobertSheaO** [comment]
I will test with an emulator and try to repro

**Comment by mkpietrzyk** [comment]
`    Activity activity = getCurrentActivity();

    if(activity != null){
      Intent contactIntent = new Intent(getReactApplicationContext(), ContactZendeskActivity.class);
      contactIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
      getReactApplicationContext().startActivity(contactIntent);
    }`

**Comment by mkpietrzyk** [comment]
Any Updates?

**Comment by MasahiroMorita** [comment]
Me too! I faced the same problem.
Any updates?

![screenshot_2017-10-25-14-21-11](https://user-images.githubusercontent.com/1058058/31981901-dfd58122-b990-11e7-91b1-5f56b137f3c5.png)

**Comment by RobertSheaO** [comment]
Sorry for the delay folks. Day job got me busy for the past week. I'll go ahead and implement the solution that @mkpietrzyk suggested. You can expect an update tomorrow. Thanks for finding this bug!

**Comment by mkpietrzyk** [comment]
No worries mate :) If you would like to answer the first closed issue about callSupport and custom fields, that would be perfect. I can't refrence it since im on the phone right now. 

Thank for accepting the solution! :)

**Comment by itchingpixels** [comment]
we've also bumped into the same issue, getting a crash on Android 6.0 (so far device independent)

**Comment by mkpietrzyk** [comment]
#12 I've created a PR  covering callSupport and supportHistory :)

**Comment by mkpietrzyk** [comment]
[This commit solves the issue](https://github.com/mkpietrzyk/react-native-zendesk-support/commit/12b2be83421b6998ee288736884c7a87904b1260)

**Comment by mkpietrzyk** [comment]
https://github.com/mkpietrzyk/react-native-zendesk-support/commit/12b2be83421b6998ee288736884c7a87904b1260

This and last 3 commits solves the issue

**Comment by itchingpixels** [comment]
We're trying to use the latest commit from master, but it fails to compile with the following error:
```
/Users/mark/Dev/drops-react-native/node_modules/react-native-zendesk-support/android/src/main/java/com/robertsheao/RNZenDeskSupport/RNZenDeskSupportModule.java:236: error: illegal start of expression
    if(activity !== null){
                  ^
/Users/mark/Dev/drops-react-native/node_modules/react-native-zendesk-support/android/src/main/java/com/robertsheao/RNZenDeskSupport/RNZenDeskSupportModule.java:248: error: illegal start of expression
    if(activity !== null){
                  ^
2 errors
:react-native-zendesk-support:compileReleaseJavaWithJavac FAILED
```

**Comment by RobertSheaO** [comment]
@itchingpixels Try it now, I changed it to `!=`

**Comment by itchingpixels** [comment]
It compiles now, thank you! Will report back when QA verified that the crash is gone.

**Comment by RobertSheaO** [comment]
Just a heads up, I try my best to make sure master is stable, but I do
additional testing before publishing to the NPM Registry that would be
beneficial if you’re actively reliant on this package; however, you can
always specify a specific commit hash in your package.json or yarn.lock if
you’d still like to reference from GitHub.

**Comment by itchingpixels** [comment]
thanks for the info, we do specificy commit hashes:)

**Comment by itchingpixels** [comment]
We can still reproduce this as far as I see: 

![image](https://user-images.githubusercontent.com/5416288/32449168-c8cd56fe-c308-11e7-856a-7df680b02202.png)

**Comment by RobertSheaO** [comment]
This hasn’t been released to NPM yet, are you referencing from there or
Github?

**Comment by itchingpixels** [comment]
Yes, I can confirm that we're using the latest master, where the new code
checking if activity is null.

**Comment by mkpietrzyk** [comment]
@itchingpixels which API are you using to reproduce it? The fix I made fixed the problem for me for Marshmallow on Galaxy A3 (2016). I don't have any other device on Android 6.x and on 7.x the Error just did not show.

**Comment by itchingpixels** [comment]
Yes, confirmed. We're running API 23.

The reason why the crash is there is that not all of the methods have the added
```    Activity activity = getCurrentActivity();

    if(activity != null){```
check.

We're using showHelpCenterWithOptions that was untouched in the last 3-4 commits.

**Comment by itchingpixels** [comment]
The extra null check has only been added to  `supportHistory` & `callSupport`

**Comment by itchingpixels** [comment]
can someone else confirm?

**Comment by mkpietrzyk** [comment]
Ok, do callSupport and supportHistory are working fine? 

Unfortunately I can't test the other since I did not had any plans od using extended FAQ from Zendesk. I guess we can utilize the same statement to the test of methods :)

**Comment by RobertSheaO** [comment]
@itchingpixels I'm trying to figure out how I'd call the `new SupportActivity.Builder().show()` methods using an `Intent` but am coming up empty handed. Do you have any insight into how this can be accomplished. Tomorrow I'll ask my co-worker, who has more Java insight, what he thinks a good solution would be.

**Comment by RobertSheaO** [comment]
Quick update. It's morning where I'm at and I've got my hands on a Marshmallow device! Testing this crash as we speak and coming up with a solution.

**Comment by RobertSheaO** [comment]
The latest and greatest release on NPM, version 1.0.5 has fixes for this bug!

**Comment by itchingpixels** [comment]
Hi! Thank you!

It seems like the content of this PR: https://github.com/RobertSheaO/react-native-zendesk-support/pull/16 has been reverted with the this commit:
https://github.com/RobertSheaO/react-native-zendesk-support/commit/fc6cd69aee58a2413fd5053961fd36d272a6e12a, was that intentional?

**Comment by RobertSheaO** [comment]
@itchingpixels That was certainly not intended. I'll patch and release 1.0.6 to fix this.

**Comment by itchingpixels** [comment]
Thank you!:)
