### ISSUE TITLE
Custom Fields not updating (iOS)

### ISSUE THREAD

**Issue by mkpietrzyk** [RobertSheaO/react-native-zendesk-support#13]
Hello again,

@RobertSheaO 

Refrencing to #1, I have tried exactly the same thing as you suggested to pass the metadata using DeciveInfo through custom fields.

Unfortunately, using your example does not update any of the fields on Zendesk ticket side after receiving one on ticket site.

For example my version custom ticket ID number is 1423213 ( the one from Zendesk site, right under the title which is 'App Version') 

when using code

```

const version = DeviceInfo.getVersion().toString();
const customFields = {
  1423213: version,
};
ZendeskSupport.callSupport(customFields);


```

The ticket passes with description, but the 'App Version' field is not updated and stay blank while reviewing the ticket. 

I have tried with plain Strings, even putting 1423213 as string but nothing seems to pass the data.

The 'App Version' ticket is **enabled** and is **editable** for End-Users.
I have the identity setup working as well as initialize. 

Am I doing something wrong?

**Update** : I have hard-coded fields for iOS and Android on both modules by following [Zendesk SDK docs](https://developer.zendesk.com/embeddables/docs/android/requests) ignoring your methods to convert object to list, and it seems to work. But if it works for you without any changes, please provide some code sample.

**Comment by mkpietrzyk** [comment]
Ok it seems that It is working fine... I do not know what happened. It just started working again. 

Mea culpa. To the close we go.

**Comment by mkpietrzyk** [comment]
Ok this is odd. On Android device it seems to be working now, yet I can't still get this to work on iOS. Is that may be the case that I am on emulator?

**Comment by Jlexyc** [comment]
doens't work for iOS.. I'll take a look. Finished with adding tags and subject for ticket. Will check custom field. Waiting on review my first fix from author. Will create next PR after.

**Comment by RobertSheaO** [comment]
I’m also now seeing this occur. Investigating

**Comment by RobertSheaO** [comment]
Found the problem. Not a problem with this package. The custom field needs to be configured as both Visible and Editable in the Zendesk admin panel.

See Mathew Cropper's reply on this thread:
https://support.zendesk.com/hc/en-us/community/posts/239418608-Android-SDK-setCustomFields-does-not-work
