### ISSUE TITLE
Android: calling startActivity() from outside of an Activity context

### ISSUE THREAD

**Issue by Lastin** [RobertSheaO/react-native-zendesk-support#17]
I get this error when calling `ZendeskSupport.showHelpCenter()`
<img src="https://user-images.githubusercontent.com/5638394/32549866-e79f24f6-c482-11e7-88fc-3518d4f070e8.png" width="250"/>

Application uses https://github.com/wix/react-native-navigation with custom lifecycle facade.
Also multidex is enabled.

Any ideas what might be causing this, and how to solve it?

**Comment by RobertSheaO** [comment]
This is tracked as issue #10

**Comment by RobertSheaO** [comment]
The issue is fixed in 1.0.5
