### ISSUE TITLE
Android build - zendesk lib can't be found

### ISSUE THREAD

**Issue by itchingpixels** [RobertSheaO/react-native-zendesk-support#2]
Hi!

By default the project didn't compile after using `react-native link`, we had to specify the zendesk maven repository url in our main app's build.gradle to make it work:

```
repositories {
    maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
}
```

Did anyone else encountered a similar issue?
If yes, it'd be worth including it in the README

**Comment by RobertSheaO** [comment]
As part of the readme, I do indicate that you need to follow the SDK install directions; however, I didn't particularly mention that you need to follow the Gradle portion. I'll add that to the README. Thanks!
