### ISSUE TITLE
Question: How to initialize the SDK?

### ISSUE THREAD

**Issue by itchingpixels** [RobertSheaO/react-native-zendesk-support#7]
It seems like there the "initialize" method is not exported via the RN bridge, what's the correct way to pass the API key, URL, etc?

```
     ZDKConfig.instance()
        .initialize(withAppId: "1e41a02a5f85d58e009ed4fa",
                    zendeskUrl: "https://omniwear.zendesk.com",
                    clientId: "mobile_sdk_client_e1c4e6262f1d02f43496")
```

This is a noob question but I haven't found any documentation about it.

**Comment by RobertSheaO** [comment]
Your example is the Swift integration of the ZenDesk Support SDK. You'll need to follow the Objective-C example as React Native is written in Objective-C.

### AppDelegate.m
```
#import <ZendeskSDK/ZendeskSDK.h>
// Other imports

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  // Other code

  [[ZDKConfig instance] initializeWithAppId:@"your_app_id" zendeskUrl:@"your_zendesk_url" clientId:@"your_client_id"];

  return YES; // This is already in your code
}
```

**Comment by itchingpixels** [comment]
Ok, understand. It wasn't clear that we'll need to initalize this on the native side, especially because it's not the kind of SDK that should delay startup time.

Are there any plans to add the initalize method on the JS side?

**Comment by RobertSheaO** [comment]
I'll clarify the first sentence of the "Getting Started" in the README to state that you need to follow those instructions for your own project. As for an initialize method in JS? I'll check it out and see if it's doable, it would be great to get rid of any unnecessary steps.

**Comment by RobertSheaO** [comment]
@itchingpixels You can now initialize the SDK through the module. Check out the updated README for more info.

P.S. On the android side, you'll need to add/keep a repository (noted in the README)
