### ISSUE TITLE
framework not found ZendeskProviderSDK for architecture x86_64

### ISSUE THREAD

**Issue by kkjdaniel** [RobertSheaO/react-native-zendesk-support#8]
I have tried to initialise the project using RNPM, however it seems unable to find the the framework? Are there any other steps I should undertake? I have tried cleaning the project, but still no luck.

```
ld: framework not found ZendeskProviderSDK for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kkjdaniel** [comment]
I noticed here (https://github.com/RobertSheaO/react-native-zendesk-support/issues/7) that you mentioned you had set it up to initialise the SDK automatically? I have managed to solve my issue by manually adding the framework. However, unless I am mistaken that isn't meant to be the usual functionality?

**Comment by RobertSheaO** [comment]
Hello @kkjdaniel, the ability of the SDK to initialize itself is a new feature, and this may be a bug. I'll run some further tests on it and get back to you.

**Comment by RobertSheaO** [comment]
I ran some tests and it appears that I missed a crucial part of the iOS setup. You'll need to integrate the Zendesk SDK via Fabric, CocoaPods, or Manually per their instructions. I tried testing adding a relative "Library Search Path" to the node_modules directory and then it wanted me to add them to my Build Phases > Link Binary With Libraries section, which is basically the same thing you have to do in the manual linking process when integrating the Zendesk SDK.

To save the hassle of redistributing their SDK inside my package, I'll remove it and just have everyone integrate the SDK per the official Zendesk instructions. Keep in mind, you won't have to follow their `[Must do] Initialize the SDK` or `[Must do] Set an identity (authentication)` sections, as that is what this package does

**Comment by RobertSheaO** [comment]
I've updated the README with updated instructions regarding iOS and published a new version (no code changes) to the NPM registry as 1.0.3
