### ISSUE TITLE
Always empty Help Centre?

### ISSUE THREAD

**Issue by kkjdaniel** [RobertSheaO/react-native-zendesk-support#9]
Despite having content available on the web version, I seem unable to display any content inside the help centre within the app?

<img src="https://user-images.githubusercontent.com/7441747/31441283-9c2f3eb0-ae8a-11e7-8f92-283040c0f394.png" width="250">

Any suggestions? I am able to setup new tickets but just not content.

**Comment by RobertSheaO** [comment]
When you load the help center, do you get a "unable to load categories" or similar message? This looks like you're not calling `setupIdentity` before you call the help center. If you're not able to see content, even after creating a ticket, then your help center content might not be configured correctly inside Zendesk.

What call are you making to load the help center? Perhaps you didn't pass a category id?

Here's an example from code that I am actively using

```js
import React from 'react'
import { View, Button } from 'react-native'
import ZendeskSDK from 'react-native-zendesk-support'
export default class SupportScreen extends Component {
  componentWillMount () {
    const { facebookData } = this.props
    const config = {
      appId: 'your_app_id',
      zendeskUrl: 'https://your_zendesk_url.zendesk.com',
      clientId: 'your_client_id'
    }
    const identity = {
      customerEmail: facebookData.getIn(['email']),
      customerName: facebookData.getIn(['name'])
    }
    ZendeskSDK.initialize(config)
    ZendeskSDK.setupIdentity(identity)
  }
  render () {
    return (
      <View>
        <Button
          title='FAQ'
          onPress={() => ZendeskSDK.showCategoriesWithOptions(
            ['your_category_id'],
            {
              showConversationsMenuButton: false,
              hideContactSupport: true,
              withContactUsButtonVisibility: 'OFF'
            }
          )}
        />
      </View>
    )
  }
}
```

**Comment by RobertSheaO** [comment]
@kkjdaniel Any update on your end? I'm thinking you've not enabled guide in your Zendesk settings and will close it as such. Feel free to reopen the issue if it persists.

**Comment by fzzf0618** [comment]
I have the same problem, I switched it to other models of iPhone to solve this problem, but i still don't know why it's empty :)

**Comment by kkjdaniel** [comment]
@RobertSheaO - Sorry, I have been preoccupied with a few other tasks as of recent. I have taken a look and the issue still persists, the implementation is very much like above. The identity however, is just an anonymous user I have setup - with some random credentials as currently I have not enabled authentication for Zendesk.

As it happens, I hadn't enabled the guide however even after enabling it I still don't get any content in the help centre? I am currently testing using the simulator.

**Comment by kkjdaniel** [comment]
Mysteriously, it's started working. Not sure which variable it was exactly but after a fresh NPM Install and Pod installation it seems to now be displaying content correctly. That or there is a slight delay after enabling the guide? - I would recommend anyone who experiences the to ensure the following...

1. Reinstall / Update NPM Package
2. Reinstall / Update Pod
3. Enable the Guide in the Mobile SDK Settings (as pictured below)

![screen shot 2017-10-18 at 1 10 35 pm](https://user-images.githubusercontent.com/7441747/31717951-ed072502-b405-11e7-8cf2-0e1d1275a74c.png)
